---
openapi: "3.0.3"
info:
  title: "allOf discriminator with entry document schemas (components file)"
  version: "0.0.1"
components:
  schemas:
    foo:
      type: object
      required: [fooType]
      properties:
        fooType:
          type: string
          enum:
          - bar
          - baz
      discriminator:
        propertyName: fooType
paths: {}
