openapi: 3.0.3
info:
  title: OASComply assessment entry: security scheme, component to entry
security:
  foo: []
paths:
  $ref: "paths.yaml#/paths/~1endpoint"
components:
  securitySchemes:
    foo:
      type: http
      scheme: basic
