openapi: 3.0.3
info:
  title: "OASComply assessment entry: security scheme, component to entry"
  version: "0.0.1"
security: [{foo: []}]
paths:
  /endpoint:
    $ref: "paths.yaml#/paths/~1endpoint"
components:
  securitySchemes:
    foo:
      type: http
      scheme: basic
