---
openapi: "3.0.3"
info:
  version: "0.0.1"
  title: "allOf discriminator with same-document components (components file)"
components:
  schemas:
    foo:
      type: object
      required: [fooType]
      properties:
        fooType:
          type: string
          enum:
          - bar
          - baz
      discriminator:
        propertyName: fooType
    bar:
      allOf:
      - $ref: "#/components/schemas/foo"
      properties:
        fooType:
          enum: [bar]
    baz:
      allOf:
      - $ref: "#/components/schemas/foo"
      properties:
        fooType:
          enum: [baz]
paths: {}
