---
openapi: "3.0.3"
info:
  title: "oneOf discriminator with local components (OpenAPI Entry File)"
  version: "0.0.1"
paths:
  /foo:
    get:
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: components.yaml#/components/schemas/foo
