---
openapi: "3.0.3"
info:
  version: "0.0.1"
  title: "External reference assessment case: {case}"
paths:
  /foos:
    get:
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required: [fooType]
                properties:
                  fooType:
                    type: string
                    enum:
                    - bar
                    - baz
                discriminator:
                  propertyName: fooType
                  mapping:
                    bar: "#/components/schemas/bar"
                    baz: "#/components/schemas/baz"
                oneOf:
                - properties:
                    fooType:
                      enum: [bar]
                - properties:
                    fooType:
                      enum: [baz]
