openapi: 3.0.3
info:
  title: OASComply assessment entry: operationId from $ref'd Path Item
paths:
  /foos:
    get:
      operationId: getFoos
      responses:
        "200":
          description: Ok
  /bars:
    get:
      responses:
        "200":
          description: Ok
            linkViaRef:
              operationRef: "#/paths/~1foos/get"
            linkViaId:
              operationRef: "#/paths/~1foos/get"
