openapi: 3.0.3
info:
  title: "OASComply assessment entry: operationId from 3rd $ref'd document"
  version: "0.0.1"
paths:
  /foos:
    $ref: "paths.yaml#/paths/~1foos"
  /others:
    $ref: "others.yaml#/paths/~1others"
