openapi: 3.0.3
info:
  title: OASComply assessment entry: operationId from $ref'd Path Item
paths:
  /bars:
    get:
      responses:
        "200":
          description: Ok
            linkViaRef:
              operationRef: "paths.yaml#/paths/~1foos/get"
            linkViaId:
              operationRef: "paths.yaml#/paths/~1foos/get"
