---
openapi: "3.0.3"
info:
  title: "oneOf discriminator with local components (Single File)"
  version: "0.0.1"
components:
  schemas:
    bar:
      properties:
        fooType:
          enum: [bar]
    baz:
      properties:
        fooType:
          enum: [baz]
paths:
  /foo:
    get:
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required: [fooType]
                properties:
                  fooType:
                    type: string
                    enum:
                    - bar
                    - baz
                discriminator:
                  propertyName: fooType
                  mapping:
                    bar: "#/components/schemas/bar"
                    baz: "#/components/schemas/baz"
                oneOf:
                - $ref: "#/components/schemas/bar"
                - $ref: "#/components/schemas/baz"
