openapi: 3.0.3
info:
  title: "OASComply assessment paths: operationId to a non-$ref'd operation"
  version: "0.0.1"
paths:
  /foos:
    get:
      responses:
        "200":
          description: Ok
          links:
            linkToBars:
              operationId: getBars
  /bars:
    get:
      operationId: getBars
      responses:
        "200":
          description: Ok
