openapi: 3.0.3
info:
  title: "OASComply assessment entry: operationId from $ref'd Path Item"
  version: "0.0.1"
paths:
  /foos:
    get:
      operationId: getFoos
      responses:
        "200":
          description: Ok
          links:
            linkToBars:
              operationRef: "#/paths/~1bars/get"
  /bars:
    get:
      operationId: getBars
      responses:
        "200":
          description: Ok
          links:
            linkToFoos:
              operationRef: "#/paths/~1foos/get"
