---
openapi: 3.1.0
info:
  title: "OASComply assessment entry: schema document root $id and base URI"
  version: "0.1.1"
paths:
  /endpoint:
    get:
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: schema.json#/$defs/foo/$defs/bar
