---
openapi: "3.0.3"
info:
  title: "allOf discriminator with same-document components (single doc)"
  version: "0.0.1"
paths:
  /foos:
    get:
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required: [fooType]
                properties:
                  fooType:
                    type: string
                    enum:
                    - bar
                    - baz
                discriminator:
                  propertyName: fooType
