openapi: 3.0.3
info:
  title: "OASComply assessment output: security scheme, component to entry"
  version: "0.0.1"
paths:
  /endpoint:
    get:
      security: foo
      responses:
        "200":
          description: Ok
components:
  securitySchemes:
    foo:
      type: http
      scheme: basic
