openapi: 3.0.3
info:
  title: OASComply assessment 3rd doc: operationId from 3rd $ref'd document
paths:
  /bars:
    get:
      operationId: getBars
      responses:
        "200":
          description: Ok
  /others:
    get:
      operationId: getOthers
      responses:
        "200":
          description: Ok
